Repository alexakasanjeev/Interviewee-Questions, pull requests merged in 2019-10, with the labels that each got.

#11 Added new question for HR
  README.md
Labels: changes requested, hacktoberfest

#23 Added one question
  README.md
Labels: hacktoberfest

#20 Added new question
  README.md
Labels: good first issue, hacktoberfest

#18 AddedANewQuestion
  README.md
Labels: hacktoberfest

#19 added new questions
  README.md
Labels: hacktoberfest

#13 added ques 13
  README.md
Labels: hacktoberfest

#12 Added a new question
  README.md
Labels: hacktoberfest

#24 new Question for Hr
  README.md
Labels: changes requested
